### ISSUE TITLE
the command is always reported as changed

### ISSUE THREAD

**Issue by JanMalte** [gaqzi/ansible-ssh-config#25]
using this great command to set up `.ssh/config` is always reporting as changed to ansible.
It should only report as changed, if the file was changed.

**Comment by gaqzi** [comment]
@JanMalte could you please share the command you're using? a little easier to debug from that :)

**Comment by JanMalte** [comment]
```
- name: add gitlab.company.de to ssh config
  ssh_config: host=gitlab.company.de
              hostname=queen.company.de
              port=2215
              remote_user=git
              identity_file=/root/.ssh/id_gitlab_deploy
              user=root
              state=present
  tags: ssh
```

**Comment by dabrowne** [comment]
Did you get anywhere with this? I'm currently experiencing the same issue with the below config:

```
- name: Add deploy keys to ssh config
  ssh_config:
    user: "{{ ansible_user }}"
    host: "{{ item.host }}"
    hostname: github.com
    identity_file: "~/.ssh/{{ item.identity_file }}"
    strict_host_key_checking: true
    state: present
  with_items:
    - host: repo1.github.com
      identity_file: repo1_deploy.github.id_rsa
    - host: repo2.github.com
      identity_file: repo2_deploy.github.id_rsa
```
